export const PRODUCTS = [
  {
    id: 1,
    name: "Laptop1",
    description: "A powerful laptop for all your needs.",
    price: 1999,
    quantity: 0,
    category: "Electronics",
    image: "https://via.placeholder.com/300",
  },
  {
    id: 2,
    name: "Laptop2",
    description: "A powerful laptop for all your needs.",
    price: 2999,
    quantity: 0,
    category: "Electronics",
    image: "https://via.placeholder.com/300",
  },
  {
    id: 3,
    name: "Laptop3",
    description: "A powerful laptop for all your needs.",
    price: 3999,
    quantity: 0,
    category: "Electronics",
    image: "https://via.placeholder.com/300",
  },
  {
    id: 4,
    name: "Laptop4",
    description: "A powerful laptop for all your needs.",
    price: 4999,
    quantity: 0,
    category: "Electronics",
    image: "https://via.placeholder.com/300",
  },
  {
    id: 5,
    name: "Laptop5",
    description: "A powerful laptop for all your needs.",
    price: 5999,
    quantity: 0,
    category: "Electronics",
    image: "https://via.placeholder.com/300",
  },
  {
    id: 6,
    name: "Laptop6",
    description: "A powerful laptop for all your needs.",
    price: 6999,
    quantity: 0,
    category: "Electronics",
    image: "https://via.placeholder.com/300",
  },
  {
    id: 7,
    name: "Clothing 1",
    description: "A smart smartphone with great features.",
    price: 999,
    quantity: 0,
    category: "Clothing",
    image: "https://via.placeholder.com/300",
  },
  {
    id: 8,
    name: "Clothing 2",
    description: "A smart smartphone with great features.",
    price: 999,
    quantity: 0,
    category: "Clothing",
    image: "https://via.placeholder.com/300",
  },
  {
    id: 9,
    name: "Clothing 3",
    description: "A smart smartphone with great features.",
    price: 999,
    quantity: 0,
    category: "Clothing",
    image: "https://via.placeholder.com/300",
  },
  {
    id: 10,
    name: "Clothing 4",
    description: "A smart smartphone with great features.",
    price: 999,
    quantity: 0,
    category: "Clothing",
    image: "https://via.placeholder.com/300",
  },
  {
    id: 11,
    name: "Clothing 5",
    description: "A smart smartphone with great features.",
    price: 999,
    quantity: 0,
    category: "Clothing",
    image: "https://via.placeholder.com/300",
  },
  {
    id: 12,
    name: "Clothing 6",
    description: "A smart smartphone with great features.",
    price: 999,
    quantity: 0,
    category: "Clothing",
    image: "https://via.placeholder.com/300",
  },
  {
    id: 13,
    name: "Book 1",
    description: "A smart smartphone with great features.",
    price: 999,
    quantity: 0,
    category: "Book",
    image: "https://via.placeholder.com/300",
  },
  {
    id: 14,
    name: "Book 2",
    description: "A smart smartphone with great features.",
    price: 999,
    quantity: 0,
    category: "Book",
    image: "https://via.placeholder.com/300",
  },
  {
    id: 15,
    name: "Book 3",
    description: "A smart smartphone with great features.",
    price: 999,
    quantity: 0,
    category: "Book",
    image: "https://via.placeholder.com/300",
  },
  {
    id: 16,
    name: "Book 4",
    description: "A smart smartphone with great features.",
    price: 999,
    quantity: 0,
    category: "Book",
    image: "https://via.placeholder.com/300",
  },
  {
    id: 17,
    name: "Book 5",
    description: "A smart smartphone with great features.",
    price: 999,
    quantity: 0,
    category: "Book",
    image: "https://via.placeholder.com/300",
  },
  {
    id: 18,
    name: "Book 6",
    description: "A smart smartphone with great features.",
    price: 999,
    quantity: 0,
    category: "Book",
    image: "https://via.placeholder.com/300",
  },
];
